FROM node:alpine AS builder

WORKDIR /app

RUN apk add --no-cache yarn

COPY package.json yarn.lock .env.production ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn prisma generate

RUN yarn build

RUN yarn install --production

FROM node:alpine AS production

RUN apk add --no-cache yarn

WORKDIR /app

COPY --from=builder /app/dist/src ./dist/
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.env.production ./.env.production
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["node", "dist/main"]